<?php

/**
 * Implements hook_menu().
 */
function training6_menu() {
  $menu['translation'] = array(
    'title' => 'Translation',
    'page callback' => 'training6_translation_task_page',
    'access callback' => TRUE,
  );
  $menu['registration_date'] = array(
    'title' => 'Dates',
    'page callback' => 'training6_registration_date_page',
    'access callback' => TRUE,
  );
  $menu['textarea_and_button'] = array(
    'title' => 'Textarea and Button',
    'page callback' => 'training6_textarea_and_button_page',
    'access callback' => TRUE,
  );
  return $menu;
}

/**
 * Callback function for /translation.
 */
function training6_translation_task_page() {

  $output = format_plural(rand(0, 100), '1 task', '@count tasks');
  $output_divide = explode(' ', $output);
  $output = '__' . $output_divide[0] . '__' . $output_divide[1];

  return $output;
}

/**
 * Callback function for /registration_date.
 */
function training6_registration_date_page() {

  global $user;
  $r_date = format_date($user->created, 'custom', 'j F Y', $user->timezone, 'ru');

  $now = getdate(REQUEST_TIME);
  $new_year = mktime(0, 0, 0, 1, 1, ($now['year'] + 1));
  $days_till_new_year = round(($new_year - REQUEST_TIME) / 86400);

  $content = array(
    'greeting' => array(
      '#type' => 'item',
      '#markup' =>  t('Hello, !user!', array('!user' => $user->name)),
    ),
    'reg_date' => array(
      '#type' => 'item',
      '#title' => t('Your registration date:'),
      '#markup' =>  $r_date,
    ),
    'new_year' => array(
      '#type' => 'item',
      '#title' => t('Days till New Year:'),
      '#markup' => $days_till_new_year,
    ),
  );

  // I don't know why, but the task was to push this data to the javascript level.
  $to_add_to_js = array(
    'r_date' => $r_date,
    'days_till_new_year' => $days_till_new_year,
  );
  drupal_add_js(drupal_get_path('module', 'training6') . '/js/training6.js');
  drupal_add_js($to_add_to_js, 'setting');

  return $content;
}

/**
 * Callback function for /textarea_and_button.
 */
function training6_textarea_and_button_page() {

  drupal_add_js(drupal_get_path('module', 'training6') . '/js/training6.js');

  $form = array(
    'info' => array(
      '#type' => 'item',
      '#markup' => t('The name of the button will be replaced with the text in
      textarea after every click on textarea.'),
    ),
    'textarea' => array(
      '#type' => 'textarea',
      '#value' => t('Text to replace'),
      '#attributes' => array('id' => 'magical_textarea'),
    ),
    'button' => array(
      '#type' => 'button',
      '#value' => t('Text to replace'),
      '#attributes' => array('id' => 'magical_button'),
    ),
  );

  return $form;
}
