<?php

/**
 * Available lottery codes.
 */
define('TRAINING7_LOTTERY_WIN_CODE', 'win');
define('TRAINING7_LOTTERY_LOOSE_CODE', 'loose');

/**
 * Implements hook_menu().
 */
function training7_menu() {

  $menu['lottery'] = array(
    'title' => 'Lottery',
    'page callback' => 'training7_lottery_page',
    'access callback' => TRUE,
  );

  return $menu;
}

/**
 * Implements hook_block_info().
 */
function training7_block_info() {

  $blocks['lottery_table'] = array(
    'info' => t('Lotteries'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'lottery',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function training7_block_view($delta = '') {

  if ($delta == 'lottery_table') {
    $block['subject'] = t('Lotteries');
    $block['content'] = training7_block_contents($delta);

    return $block;
  }
}

/**
 * Callback function for Lottery Table block.
 */
function training7_block_contents($delta = '') {

  if ($delta == 'lottery_table') {
    $header = array(
      'Lottery_ID',
      'User_ID',
      'Date and time',
      'Result',
    );
    $data = cache_get('lottery_list');
    if (!$data) {
      $rows = array();
    }
    else {
      $lotteries = $data->data;
      foreach ($lotteries as $lottery) {
        $rows[] = array(
          $lottery['lottery_ID'],
          $lottery['user_ID'],
          $lottery['time'],
          $lottery['result'],
        );
      }
    }
    $content = array(
      '#theme' => 'table',
      '#header' => $header,
      '#rows' => $rows,
    );
    return $content;
  }
}

/**
 * Page callback function for /lottery.
 */
function training7_lottery_page() {

  global $user;
  $role=user_role_load_by_name('authenticated user');
  if (user_has_role($role->rid)) {
    rules_invoke_event('training7_user_visited_lottery');
    $link = l(t('Try once more'), current_path());
    $lottery_message = cache_get($user->uid . '_is_winner');

    if ($lottery_message) {
      $message = $lottery_message->data . ' ' . $link;
    }
    else {
      $message = 'You have never won in lottery. ' . $link;
    }
  }
  else {
    $message = 'Sorry, only authenticated users can take part in lottery. ';
  }
  return $message;
}

/**
 * Implements hook_xmlrpc().
 */
function training7_xmlrpc() {

  $methods[] = array(
    'training7_lottery_run.generate',
    '_training7_lottery_run_callback',
    array(
      'string',
      'int',
    ),
    t('Returns result of second lottery run.'),
  );

  return $methods;
}

/**
 * XML-RPC callback for training7_lottery_run.generate.
 */
function _training7_lottery_run_callback($rand) {
  $lottery_code = $rand == rand(1, 8) ? TRAINING7_LOTTERY_WIN_CODE : TRAINING7_LOTTERY_LOOSE_CODE;
  return $lottery_code;
}
